# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_DB: polylink
      POSTGRES_PASSWORD: postgres
    ports:
      - 9091:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data: {}
